import pandas as pd
scores = pd.read_excel('data/scores.xlsx')
print(scores)
print(scores[['Chi', 'Eng', 'Math']].sum(axis=0))
print(scores[['Chi', 'Eng', 'Math']].sum(axis=1))
scores['Max'] = scores[['Chi', 'Eng', 'Math']].max(axis=1)
scores['Min'] = scores[['Chi', 'Eng', 'Math']].min(axis=1)
scores['Avg'] = scores[['Chi', 'Eng', 'Math']].mean(axis=1)
print(scores)
scores.to_excel('data/scores統計.xlsx')
print(scores[['Chi', 'Eng', 'Math']].sum(axis=1))
scoresmax= scores[['Chi', 'Eng', 'Math']].max(axis=0)
scoresmin = scores[['Chi', 'Eng', 'Math']].min(axis=0)
print(scoresmax)
print(scoresmin)
print(scoresmax - scoresmin)
print(scores[['Chi', 'Eng', 'Math']].apply(lambda x:x.max()-x.min(),axis=0))
scoresmax= scores[['Chi', 'Eng', 'Math']].max(axis=1)
scoresmin = scores[['Chi', 'Eng', 'Math']].min(axis=1)
print(scoresmax - scoresmin)
print(scores[['Chi', 'Eng', 'Math']].apply(lambda x:x.max()-x.min(),axis=1))
print(scores[['Chi', 'Eng', 'Math']].applymap(lambda x:'{0:.1f}'.format(x)))
f = lambda x:'{0:.1f}'.format(x)
print(scores[['Chi', 'Eng', 'Math']].applymap(f))
